import Head from "next/head";
import Image from "next/image";
import { Heading } from "@chakra-ui/react";
import Navbar from "../navigation/Navbar";
import Footer from "../navigation/Footer";

import { Box, useColorModeValue, ColorModeScript } from "@chakra-ui/react";

import theme from "../theme";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="">
        <h1 className="text-[50px] font-serif font-semibold text-green-500">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <Heading as="h1" size="2xl" mb="2">
          Czeeeść witam!
        </Heading>

        <p className="">
          Get started by editing <code className="">pages/index.js</code>
        </p>

        <div className=""></div>
      </main>

      <Footer />
    </div>
  );
}
